import json
import re
from deep_translator import GoogleTranslator
import time

translator = GoogleTranslator(source='en', target='ko')

filepath = '/Users/pochoco/Desktop/원소주기율표/elements_data.js'
with open(filepath, 'r', encoding='utf-8') as f:
    js_content = f.read()

match = re.search(r'const elementsData = (\[[\s\S]*?\]);', js_content)
if not match:
    print("Could not find elementsData array")
    exit(1)

data_str = match.group(1)
# Handle potential JS specifics in the array string if any. 
# But it's mostly strict JSON if generated by my previous node script.
try:
    elements = json.loads(data_str)
except json.JSONDecodeError as e:
    print(f"Failed to parse JSON: {e}")
    exit(1)

print(f"Translating {len(elements)} elements...")

# Keep a cache to avoid translating same string twice
cache = {}

def translate_field(text):
    if not text:
        return text
    if text in cache:
        return cache[text]
    try:
        translated = translator.translate(text)
        cache[text] = translated
        time.sleep(0.1) # Be nice to Google Translate API
        return translated
    except Exception as e:
        print(f"Translation failed for '{text}': {e}")
        return text

for i, el in enumerate(elements):
    if el.get('appearance'):
        el['appearance'] = translate_field(el['appearance'])
    if el.get('discovered_by'):
        el['discovered_by'] = translate_field(el['discovered_by'])
    if el.get('named_by'):
        el['named_by'] = translate_field(el['named_by'])
    if el.get('summary'):
        el['summary'] = translate_field(el['summary'])
    
    if (i+1) % 10 == 0:
        print(f"Translated {i+1} elements...")

new_data_str = json.dumps(elements, ensure_ascii=False, indent=2)
new_js_content = js_content.replace(data_str, new_data_str)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(new_js_content)

print("Translation complete and written to elements_data.js")
